### ISSUE TITLE
Add support for Vroom 1.12.0

### ISSUE THREAD

**Issue by krashish8** [pgRouting/vrprouting#34]
**From Vroom v1.12.0 release notes**: https://github.com/VROOM-Project/vroom/releases/tag/v1.12.0

Not considering backward compatibility at this stage of the project.

~Crossing out~ the entries that require no change, or can be done in the future

**Added**
- [x] ~IntraTwoOpt local search operator (#706)~ internal
- [x] ~description key for unassigned tasks in output, if provided (#403)~ changes in json output, not cpp code
- [x] ~location_index key for unassigned tasks and each step, if provided (#625)~ changes in json output, not cpp code
- [x] Shared target to makefile, for creating Position Independent Code (#617)
- [x] ~Exposing some internals for Python through compile flags (#640)~ only for python
- [x] ~Stats on local search operators use for dev/debug purposes (#658)~ internal, for debugging
- [x] Project can be compiled without routing support to limit dependencies (#676)
- [x] ~Internal max_tasks constraints derived from input to speed up local-search (#648)~ internal

**Changed**
- [x] ~Prune local search moves based on TW constraints (#583)~ internal
- [x] ~Prune local search moves based on capacity constraints (#709)~ internal
- [x] ~Refactor exception class (#639)~ internal change, nothing needed on our end
- [x] ~CI builds now run against libosrm v5.26.0 (#651)~ CI changes
- [x] ~Reduce computing time on PDPTW benchmarks by around 20% (#559)~ internal
- [x] Change Input and parser signature to simplify downstream usage (#665): Made changes according to new Input signature
- [x] ~Consider move options in SWAP* that were previously wrongly discarded (#682)~ internal
- [x] ~Use cxxopts as command line parser instead of getopt (#602)~ internal
- [x] ~Change polylineencoder usage to submodule instead of plain header (#686)~ internal

**Fixed**
- [x] ~Remove duplicate definition of LocalSearch (#638)~ internal
- [x] ~Move priority check to Job constructor instead of input parser (#628)~ internal
- [x] ~Wrong index values without custom matrix (#683)~ internal
- [x] ~Assignments instead of equality checks in some plan mode assertions (#701)~ internal
- [x] ~Initialization of single-entry matrix (#699)~ internal
